version: "3.1"
services:
  provide-credentials:
    image: postgres:13.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      WEB_FLAG: ${WEB_FLAG-you_didnt_fill_in_the_web_flag}
    ports:
      - "5432:5432"
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh